name: flutter_sample
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_i18n: ^0.20.1
  audioplayers: ^0.15.1 #flame version dependant
  webview_flutter: 1.0.7
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  flame: ^0.28.0
  vector_math: ^2.0.8
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #IMAGES
    - assets/images/ui/b3ird.png
    - assets/images/ui/logo.png
    - assets/images/ui/small_logo.png
    - assets/images/bg/background.png
    - assets/images/bg/splash.png
    - assets/images/characters/player_left.png
    - assets/images/characters/player_front.png
    - assets/images/characters/player_right.png
    - assets/images/fx/burn_explosion.png
    - assets/images/fx/blood_explosion.png
    - assets/images/fx/blood_screen.png
    - assets/images/props/meteor.png
    - assets/images/props/bonus.png
    - assets/images/props/star.png
    - assets/images/props/sun.png
    - assets/images/controller/joystick_background.png
    - assets/images/controller/joystick_knob.png
    - assets/images/controller/restart.png
    #AUDIO
    - assets/audio/music.mp3
    - assets/audio/burn.mp3
    - assets/audio/crash_1.mp3
    - assets/audio/crash_2.mp3
    - assets/audio/crash_3.mp3
    - assets/audio/meteor_1.mp3
    - assets/audio/meteor_2.mp3
    - assets/audio/meteor_3.mp3
    - assets/audio/wilhelm.mp3
    - assets/audio/splash.mp3
    - assets/audio/play.mp3
    - assets/audio/exit.mp3
    - assets/audio/bonus.mp3
    - assets/audio/get_bonus.mp3
    #TEXTS
    - assets/i18n/fr.json
    - assets/i18n/en.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
